styledown = ../../bin/styledown

public/index.html: \
	colors.css \
	buttons.css \
	nav.css \
	typography.css \
	forms.css \
	components.css \
	tables.css \
	images.css\
	icons.css\
	modal.css\
	_extras.css
	$(styledown) $^ > $@
